name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Email...
        run: git config --global user.email "tksukhu@gmail.com"

      - name: Set User...
        run: git config --global user.name "Tarun Kumar Sukhu"

      - name: Begin CI...
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn build-static
        env:
          CI: true
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out